# SQL analysis of Crime and Schools DBs

### Load SQL and datebases

In [ ]:
%load_ext sql

In [2]:
%sql ibm_db_sa://tpj63928:Imagination1!py08ma@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB

'Connected: tpj63928@BLUDB'

In [3]:
%sql select count(id) from crime

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('533'),)]

### View Crime DB

In [4]:
%sql select * from crime limit 10

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(3512276, 'HK587712', datetime.datetime(2004, 8, 28, 17, 50, 56), '047XX S KEDZIE AVE', '890', 'THEFT', 'FROM BUILDING', 'SMALL RETAIL STORE', 'FALSE', 'FALSE', 911, 9, 14, 58, '6', 1155838, 1873050, 2004, datetime.datetime(2018, 2, 10, 15, 50, 1), Decimal('41.80744050'), Decimal('-87.70395585'), '(41.8074405, -87.703955849)'),
 (3406613, 'HK456306', datetime.datetime(2004, 6, 26, 12, 40), '009XX N CENTRAL PARK AVE', '820', 'THEFT', '$500 AND UNDER', 'OTHER', 'FALSE', 'FALSE', 1112, 11, 27, 23, '6', 1152206, 1906127, 2004, datetime.datetime(2018, 2, 28, 15, 56, 25), Decimal('41.89827996'), Decimal('-87.71640551'), '(41.898279962, -87.716405505)'),
 (8002131, 'HT233595', datetime.datetime(2011, 4, 4, 5, 45), '043XX S WABASH AVE', '820', 'THEFT', '$500 AND UNDER', 'NURSING HOME/RETIREMENT HOME', 'FALSE', 'FALSE', 221, 2, 3, 38, '6', 1177436, 1876313, 2011, datetime.datetime(2018, 2, 10, 15, 50, 1), Decimal('41.81593313'), Decimal('-87.62464213'), '(41.815933131, -87.624642127)'),
 (7903289, 'HT133522', datetime.datetime(2010, 12, 30, 16, 30), '083XX S KINGSTON AVE', '840', 'THEFT', 'FINANCIAL ID THEFT: OVER $300', 'RESIDENCE', 'FALSE', 'FALSE', 423, 4, 7, 46, '6', 1194622, 1850125, 2010, datetime.datetime(2018, 2, 10, 15, 50, 1), Decimal('41.74366532'), Decimal('-87.56246276'), '(41.743665322, -87.562462756)'),
 (10402076, 'HZ138551', datetime.datetime(2016, 2, 2, 19, 30), '033XX W 66TH ST', '820', 'THEFT', '$500 AND UNDER', 'ALLEY', 'FALSE', 'FALSE', 831, 8, 15, 66, '6', 1155240, 1860661, 2016, datetime.datetime(2018, 2, 10, 15, 50, 1), Decimal('41.77345530'), Decimal('-87.70648047'), '(41.773455295, -87.706480471)'),
 (7732712, 'HS540106', datetime.datetime(2010, 9, 29, 7, 59), '006XX W CHICAGO AVE', '810', 'THEFT', 'OVER $500', 'PARKING LOT/GARAGE(NON.RESID.)', 'FALSE', 'FALSE', 1323, 12, 27, 24, '6', 1171668, 1905607, 2010, datetime.datetime(2018, 2, 10, 15, 50, 1), Decimal('41.89644677'), Decimal('-87.64493868'), '(41.896446772, -87.644938678)'),
 (10769475, 'HZ534771', datetime.datetime(2016, 11, 30, 1, 15), '050XX N KEDZIE AVE', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 1713, 17, 33, 14, '6', 1154133, 1933314, 2016, datetime.datetime(2018, 2, 10, 15, 50, 1), Decimal('41.97284491'), Decimal('-87.70860008'), '(41.972844913, -87.708600079)'),
 (4494340, 'HL793243', datetime.datetime(2005, 12, 16, 16, 45), '005XX E PERSHING RD', '860', 'THEFT', 'RETAIL THEFT', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 213, 2, 3, 38, '6', 1180448, 1879234, 2005, datetime.datetime(2018, 2, 28, 15, 56, 25), Decimal('41.82387989'), Decimal('-87.61350386'), '(41.823879885, -87.613503857)'),
 (3778925, 'HL149610', datetime.datetime(2005, 1, 28, 17, 0), '100XX S WASHTENAW AVE', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 2211, 22, 19, 72, '6', 1160129, 1838040, 2005, datetime.datetime(2018, 2, 28, 15, 56, 25), Decimal('41.71128051'), Decimal('-87.68917910'), '(41.711280513, -87.689179097)'),
 (3324217, 'HK361551', datetime.datetime(2004, 5, 13, 14, 15), '033XX W BELMONT AVE', '820', 'THEFT', '$500 AND UNDER', 'SMALL RETAIL STORE', 'FALSE', 'FALSE', 1733, 17, 35, 21, '6', 1153590, 1921084, 2004, datetime.datetime(2018, 2, 28, 15, 56, 25), Decimal('41.93929582'), Decimal('-87.71092344'), '(41.939295821, -87.710923442)')]

### View Schools DB

In [15]:
%sql select * from c_schools limit 10

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(610038, 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl', 'Chicago', 'IL', 60614, '(773) 534-5720', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', 99, 'Very Strong', '99', 'Strong', 74, 'Strong', 66, 'Strong', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.00%', Decimal('2.0'), '96.40%', '95.80%', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', Decimal('69.7'), Decimal('64.4'), Decimal('0.2'), Decimal('0.9'), 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 813, 33, 'NDA', Decimal('1171699.458'), Decimal('1915829.428'), Decimal('41.92449696'), Decimal('-87.64452163'), 7, 'LINCOLN PARK', 43, 18, '(41.92449696, -87.64452163)'),
 (610281, 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr', 'Chicago', 'IL', 60649, '(773) 535-6650', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 54, 'Strong', '66', 'Strong', 74, 'Very Strong', 84, 'Strong', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.60%', Decimal('15.7'), '95.30%', '100.00%', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', Decimal('16.8'), Decimal('16.5'), Decimal('0.7'), Decimal('1.4'), 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 521, 46, 'NDA', Decimal('1196129.985'), Decimal('1856209.466'), Decimal('41.76032435'), Decimal('-87.55673627'), 43, 'SOUTH SHORE', 7, 4, '(41.76032435, -87.55673627)'),
 (610185, 'Adlai E Stevenson Elementary School', 'ES', '8010 S Kostner Ave', 'Chicago', 'IL', 60652, '(773) 535-2280', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610185.pdf', 'Midway Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 2', 'No', 'Strong', 61, 'NDA', 'NDA', 'Average', 50, 'Weak', 36, 'NDA', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Weak', '41', '95.70%', Decimal('2.3'), '94.70%', '98.30%', '53.7', '26.6', '38.3', '34.7', '43.7', '57.3', '48.8', '39.2', '46.8', '44', '7.5', '21.9', Decimal('18.3'), Decimal('15.5'), Decimal('-0.9'), Decimal('-1.0'), 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1324, 44, 'NDA', Decimal('1148427.165'), Decimal('1851012.215'), Decimal('41.74711093'), Decimal('-87.73170248'), 70, 'ASHBURN', 13, 8, '(41.74711093, -87.73170248)'),
 (609993, 'Agustin Lara Elementary Academy', 'ES', '4619 S Wolcott Ave', 'Chicago', 'IL', 60609, '(773) 535-4389', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609993.pdf', 'Pershing Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', 56, 'Average', '44', 'Average', 45, 'Weak', 37, 'Strong', '65', 'Average', '48', 'Average', '53', 'Strong', '58', '95.50%', Decimal('10.4'), '95.80%', '100.00%', '76.9', 'NDA', '26', '24.7', '61.8', '49.7', '39.2', '27.2', '69.7', '60.6', '9.1', '18.2', Decimal('11.1'), Decimal('9.6'), Decimal('0.9'), Decimal('2.4'), 'Green', 'Green', '42.9', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 556, 42, 'NDA', Decimal('1164504.290'), Decimal('1873959.199'), Decimal('41.80975690'), Decimal('-87.67214460'), 61, 'NEW CITY', 20, 9, '(41.8097569, -87.6721446)'),
 (610513, 'Air Force Academy High School', 'HS', '3630 S Wells St', 'Chicago', 'IL', 60609, '(773) 535-1590', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610513.pdf', 'Southwest Side High School Network', 'SOUTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'Yes', 'Average', 49, 'Strong', '60', 'Strong', 60, 'Average', 55, 'Average', '45', 'Average', '54', 'Average', '53', 'Average', '49', '93.30%', Decimal('15.6'), '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.6', '14.8', 'NDA', '16', '1.4', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 302, 40, '91.8', Decimal('1175177.622'), Decimal('1880745.126'), Decimal('41.82814609'), Decimal('-87.63279369'), 34, 'ARMOUR SQUARE', 11, 9, '(41.82814609, -87.63279369)'),
 (610212, 'Albany Park Multicultural Academy', 'MS', '4929 N Sawyer Ave', 'Chicago', 'IL', 60625, '(773) 534-5108', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610212.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Strong', 66, 'Weak', '37', 'Strong', 66, 'Strong', 71, 'Average', '43', 'Average', '50', 'Weak', '46', 'Average', '51', '97.00%', Decimal('2.3'), '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '60.7', '39.8', '53.7', '59.8', '17.5', '20.8', Decimal('34.5'), Decimal('15.6'), Decimal('0.2'), Decimal('0.3'), 'Yellow', 'Yellow', '29.2', '50', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 266, 31, 'NDA', Decimal('1153858.196'), Decimal('1932691.891'), Decimal('41.97114330'), Decimal('-87.70962725'), 14, 'ALBANY PARK', 39, 17, '(41.9711433, -87.70962725)'),
 (609720, 'Albert G Lane Technical High School', 'HS', '2501 W Addison St', 'Chicago', 'IL', 60618, '(773) 534-5400', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609720.pdf', 'North-Northwest Side High School Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Very Strong', 88, 'NDA', 'NDA', 'Strong', 62, 'Average', 52, 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '96.30%', Decimal('2.1'), '96.20%', '99.40%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '19.1', '19.5', '19.9', '20.1', '1', '23.4', '3.5', '67.9', '92.2', '79.8', 4368, 35, '90.7', Decimal('1158975.392'), Decimal('1923791.705'), Decimal('41.94661693'), Decimal('-87.69105603'), 5, 'NORTH CENTER', 47, 19, '(41.94661693, -87.69105603)'),
 (610342, 'Albert R Sabin Elementary Magnet School', 'ES', '2216 W Hirsch St', 'Chicago', 'IL', 60622, '(773) 534-4491', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610342.pdf', 'Fulton Elementary Network', 'WEST SIDE COLLABORATIVE', 'No', 'Standard', 'Probation', 'Level 3', 'No', 'Strong', 67, 'NDA', 'NDA', 'Weak', 30, 'Very Weak', 18, 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '94.70%', Decimal('28.1'), '95.00%', '100.00%', '56.3', 'NDA', '33.5', '33.5', '49.5', '49.5', '27.4', '39.3', '35.5', '44.4', '25', '23.4', Decimal('18.0'), Decimal('12.8'), Decimal('-1.8'), Decimal('0.1'), 'Red', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 620, 35, 'NDA', Decimal('1161265.299'), Decimal('1909314.592'), Decimal('41.90684338'), Decimal('-87.68304259'), 24, 'WEST TOWN', 1, 14, '(41.90684338, -87.68304259)'),
 (610524, 'Alcott High School for the Humanities', 'HS', '2957 N Hoyne Ave', 'Chicago', 'IL', 60618, '(773) 534-5979', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610524.pdf', 'North-Northwest Side High School Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'No', 'Strong', 70, 'NDA', 'NDA', 'Strong', 67, 'Average', 51, 'NDA', 'NDA', 'NDA', 'NDA', 'Strong', '57', 'Weak', '43', '92.70%', Decimal('7.1'), '96.90%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '14.7', '13.7', 'NDA', '16', '1.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 232, 33, '87.6', Decimal('1161870.556'), Decimal('1919857.440'), Decimal('41.93576106'), Decimal('-87.68052441'), 5, 'NORTH CENTER', 1, 19, '(41.93576106, -87.68052441)'),
 (610209, 'Alessandro Volta Elementary School', 'ES', '4950 N Avers Ave', 'Chicago', 'IL', 60625, '(773) 534-5080', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610209.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 2', 'No', 'Average', 43, 'Strong', '61', 'Weak', 28, 'Weak', 37, 'Strong', '62', 'Average', '56', 'Average', '51', 'Average', '53', '96.40%', Decimal('22.5'), '95.90%', '100.00%', '63.9', '43.2', '51.3', '32.9', '50.7', '70', '52.5', '31.3', '59.8', '57.6', '16.5', '24.7', Decimal('19.9'), Decimal('14.2'), Decimal('0.3'), Decimal('-0.4'), 'Yellow', 'Yellow', '31.6', '65.2', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 1023, 31, 'NDA', Decimal('1149774.095'), Decimal('1932831.151'), Decimal('41.97160605'), Decimal('-87.72464139'), 14, 'ALBANY PARK', 39, 17, '(41.97160605, -87.72464139)')]

## Example queries

### Query number of arrests made

In [5]:
%sql select count(id) from crime where arrest='TRUE'

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('163'),)]

### Query number of crimes at 'Gas Station'

In [6]:
%sql select distinct(primary_type), location_description from crime where location_description = 'GAS STATION'

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('CRIMINAL TRESPASS', 'GAS STATION'),
 ('NARCOTICS', 'GAS STATION'),
 ('ROBBERY', 'GAS STATION'),
 ('THEFT', 'GAS STATION')]

### Query communities with name beginning with B

In [7]:
%sql select community_area_name from census where community_area_name like 'B%'

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Belmont Cragin',),
 ('Burnside',),
 ('Brighton Park',),
 ('Bridgeport',),
 ('Beverly',)]

### Query which schools in Community Areas 10 to 15 are healthy certified?

In [8]:
%sql select name_of_school, community_area_number, healthy_school_certified \
from c_schools \
where community_area_number >= 10 and community_area_number <= 15 \
and healthy_school_certified = 'Yes'

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Rufus M Hitch Elementary School', 10, 'Yes')]

### Query average school safety score

In [9]:
%sql select avg(safety_score) from c_schools

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('49.504873'),)]

### Query retrieve list: the top 5 Community Areas by average College Enrollment

In [10]:
%sql select community_area_name, \
cast(round(avg(college_enrollment)) as int) as average_college_enrollment \
from c_schools group by community_area_name \
order by average_college_enrollment desc limit 5

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('ARCHER HEIGHTS', 2412),
 ('MONTCLARE', 1317),
 ('WEST ELSDON', 1233),
 ('BRIGHTON PARK', 1206),
 ('BELMONT CRAGIN', 1199)]

### Sub-query: Community Area with lowest school Safety Score?

In [11]:
%sql select community_area_name, safety_score \
from c_schools \
where safety_score = (select min(safety_score) from c_schools)

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('WASHINGTON PARK', 1)]

### Query without using JOIN operator: Find the Per Capita Income of the Community Area which has a school Safety Score of 1

In [12]:
%sql select c_schools.community_area_name, census.per_capita_income, c_schools.safety_score \
from c_schools, census \
where c_schools.community_area_number = census.community_area_number \
and safety_score = 1

 * ibm_db_sa://tpj63928:***@dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('WASHINGTON PARK', 13785, 1)]